services:
  blue_app:
    image: ${APP_IMG}
    container_name: blue_app
    networks:
      - custom_network
    depends_on:
      - db
    ports:
      - ${BLUE_PORT}:8080
    environment:
      DBHOST: ${DBHOST}
      DBUSER: ${DBUSER}
      DBPORT: ${DBPORT}
      DATABASE: ${DBNAME}
      DBPWD: ${DBPWD}
      APP_COLOR: blue
    entrypoint: /bin/bash -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh my_db 3306 -- python3 app.py"
  pink_app:
    image: ${APP_IMG}
    container_name: pink_app
    networks:
      - custom_network
    depends_on:
      - db
    ports:
      - ${PINK_PORT}:8080
    environment:
      DBHOST: ${DBHOST}
      DBUSER: ${DBUSER}
      DBPORT: ${DBPORT}
      DATABASE: ${DBNAME}
      DBPWD: ${DBPWD}
      APP_COLOR: pink
    entrypoint: /bin/bash -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh my_db 3306 -- python3 app.py"
  lime_app:
    image: ${APP_IMG}
    container_name: lime_app
    networks:
      - custom_network
    depends_on:
      - db
    ports:
      - ${LIME_PORT}:8080
    environment:
      DBHOST: ${DBHOST}
      DBUSER: ${DBUSER}
      DBPORT: ${DBPORT}
      DATABASE: ${DBNAME}
      DBPWD: ${DBPWD}
      APP_COLOR: lime
    entrypoint: /bin/bash -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh my_db 3306 -- python3 app.py"
  db:
    image: ${DB_IMG}
    restart: always
    container_name: my_db
    networks:
      - custom_network
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPWD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 30s
      retries: 8
      timeout: 10s
      start_period: 20s
networks:
  custom_network:
    name: my_network
    driver: bridge