apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: final
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: [ecr/repo]
        ports:
        - containerPort: 81
        env:
          - name: DBHOST
            valueFrom:
              configMapKeyRef:
                name: app-config      # Name of the ConfigMap
                key: DBHOST  
          - name: APP_COLOR
            valueFrom:
              configMapKeyRef:
                name: app-config      # Name of the ConfigMap
                key: APP_COLOR  
          - name: APP_IMG
            valueFrom:
              configMapKeyRef:
                name: app-config      # Name of the ConfigMap
                key: APP_IMG
          - name: APP_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config      # Name of the ConfigMap
                key: APP_PORT
      imagePullSecrets:
      - name: ecr-secret